// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsRunning() {
  return window['go']['app']['App']['IsRunning']();
}

export function Resize(arg1, arg2) {
  return window['go']['app']['App']['Resize'](arg1, arg2);
}

export function StartCosmotop(arg1, arg2) {
  return window['go']['app']['App']['StartCosmotop'](arg1, arg2);
}

export function Status() {
  return window['go']['app']['App']['Status']();
}

export function StopCosmotop() {
  return window['go']['app']['App']['StopCosmotop']();
}

export function WriteInputBase64(arg1) {
  return window['go']['app']['App']['WriteInputBase64'](arg1);
}
