// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsRunning():Promise<boolean>;

export function Resize(arg1:number,arg2:number):Promise<void>;

export function StartCosmotop(arg1:number,arg2:number):Promise<void>;

export function Status():Promise<string>;

export function StopCosmotop():Promise<void>;

export function WriteInputBase64(arg1:string):Promise<void>;
