/* Copyright 2026 Brett Jia (dev.bjia56@gmail.com)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

	   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

indent = tab
tab-size = 4

This file is auto-generated by tools/generate_embeds.py
For development builds, it contains empty vectors.
For release builds, it contains embedded themes and licenses.
*/

#include <string>
#include <unordered_map>
#include <vector>

namespace cosmotop {
namespace embeds {

// Embedded theme files: filename -> content
const std::unordered_map<std::string, std::string> themes = {
	// Empty in development builds
	// Populated by tools/generate_embeds.py for release builds
};

// Embedded license files: name -> content
const std::unordered_map<std::string, std::string> licenses = {
	// Empty in development builds
	// Populated by tools/generate_embeds.py for release builds
};

// Check if embedded themes are available
bool has_embedded_themes() {
	return !themes.empty();
}

// Check if embedded licenses are available
bool has_embedded_licenses() {
	return !licenses.empty();
}

// Get embedded theme content, returns empty string if not found
std::string get_theme(const std::string& name) {
	auto it = themes.find(name);
	if (it != themes.end()) {
		return it->second;
	}
	return "";
}

// Get embedded license content, returns empty string if not found
std::string get_license(const std::string& name) {
	auto it = licenses.find(name);
	if (it != licenses.end()) {
		return it->second;
	}
	return "";
}

// Get list of embedded theme names
std::vector<std::string> get_theme_names() {
	std::vector<std::string> names;
	for (const auto& [name, _] : themes) {
		names.push_back(name);
	}
	return names;
}

// Get list of embedded license names
std::vector<std::string> get_license_names() {
	std::vector<std::string> names;
	for (const auto& [name, _] : licenses) {
		names.push_back(name);
	}
	return names;
}

} // namespace embeds
} // namespace cosmotop
